### ISSUE TITLE
Implementing `StorageIntegration` resource

### ISSUE THREAD

**Issue by LouisAmon** [nuage-studio/pulumi-snowflake#5]
https://docs.snowflake.net/manuals/sql-reference/sql/create-storage-integration.html

```python
storage_integration = StorageIntegration(
    resource_name='Acme-AWS-StorageIntegration',
    name='Acme-AWS',
    type='external_stage',
    cloud_provider_params={
        'storage_provider': 's3',
        'storage_aws_role_arn': '<iam_role>',
    },
    enabled=True,
    storage_allowed_locations='*' # or ['s3://bucket/path/', 's3://bucket/path/'],
    storage_blocked_locations=['s3://bucket/path/', 's3://bucket/path/']
)
```

**Comment by LouisAmon** [comment]
NB : Snowflake defines a form of subclass pattern for Integrations

https://docs.snowflake.net/manuals/sql-reference/sql/create-integration.html

It could make sense to define an `Integration` class that has a `type` parameter.

What do you think @cloudspeak ?

**Comment by cloudspeak** [comment]
> It could make sense to define an Integration class that has a type parameter.

We could do - although personally I don't think you gain much in this case because the only shared parameters are the type and `comment`.

**Comment by LouisAmon** [comment]
I agree with you.

I think Snowflake may be moving in this direction at some point (when NotificationIntegration it out of the preview phase), but for now let's mimic them and keep it separate.

We'll merge when they do !

**Comment by LouisAmon** [comment]
Regarding your choice of `AWSStorageIntegration` as a class name : I think we should keep to `StorageIntegration` to reflect the native objects that Snowflake users manipulate.

Also, I had something else in mind for AWS/Azure/GCloud: I'd like to make 3 Pulumi Components for each of those that performs the actual Storage Integration on both sides.

In the case of AWS, the `AWSStorageIntegration(pulumi.Component)` that I have in mind should:

1. Create a Snowflake StorageIntegration
2. Create an AWS Role `SnowflakeRole` that has suitable permissions (could default to S3 read/write, and allowing a policy to be passed as argument)

This way, the best practices are automatically set up in a scripted fashion.

What do you think @cloudspeak ?

**Comment by cloudspeak** [comment]
> Regarding your choice of AWSStorageIntegration as a class name : I think we should keep to StorageIntegration to reflect the native objects that Snowflake users manipulate.

No problem


> In the case of AWS, the `AWSStorageIntegration(pulumi.Component)` that I have in mind should:
> 
> 1. Create a Snowflake StorageIntegration
> 2. Create an AWS Role `SnowflakeRole` that has suitable permissions (could default to S3 read/write, and allowing a policy to be passed as argument)
> 
> This way, the best practices are automatically set up in a scripted fashion.

I've been thinking about this myself - I definitely like the idea!  Note that there is some additional complexity because Storage Integration objects require the Role ARN (so the role must be created first), but upon creation generates its own external ID which must be attached to the role's trust relationship document (which you have to specify when you create the role).  This causes an awkward circular dependency - my thought was that you could create an additional resource called `RoleTrustRelationshipAttachement` or similar which describes the attachment of a trust relationship to a role separately from the creation of a role, and implement the provider using Boto.  In any case it's definitely doable, just needs some thought.
